// Code generated by protoc-gen-go.
// source: model/model.proto
// DO NOT EDIT!

package model

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type RelationMember_MemberType int32

const (
	RelationMember_NODE     RelationMember_MemberType = 0
	RelationMember_WAY      RelationMember_MemberType = 1
	RelationMember_RELATION RelationMember_MemberType = 2
)

var RelationMember_MemberType_name = map[int32]string{
	0: "NODE",
	1: "WAY",
	2: "RELATION",
}
var RelationMember_MemberType_value = map[string]int32{
	"NODE":     0,
	"WAY":      1,
	"RELATION": 2,
}

func (x RelationMember_MemberType) Enum() *RelationMember_MemberType {
	p := new(RelationMember_MemberType)
	*p = x
	return p
}
func (x RelationMember_MemberType) String() string {
	return proto.EnumName(RelationMember_MemberType_name, int32(x))
}
func (x RelationMember_MemberType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *RelationMember_MemberType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RelationMember_MemberType_value, data, "RelationMember_MemberType")
	if err != nil {
		return err
	}
	*x = RelationMember_MemberType(value)
	return nil
}

type Node struct {
	Id               *int64   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Long             *uint32  `protobuf:"varint,2,req,name=long" json:"long,omitempty"`
	Lat              *uint32  `protobuf:"varint,3,req,name=lat" json:"lat,omitempty"`
	Tags             []string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}

func (m *Node) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Node) GetLong() uint32 {
	if m != nil && m.Long != nil {
		return *m.Long
	}
	return 0
}

func (m *Node) GetLat() uint32 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *Node) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Way struct {
	Id               *int64   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Tags             []string `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
	Refs             []int64  `protobuf:"varint,3,rep,packed,name=refs" json:"refs,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Way) Reset()         { *m = Way{} }
func (m *Way) String() string { return proto.CompactTextString(m) }
func (*Way) ProtoMessage()    {}

func (m *Way) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Way) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Way) GetRefs() []int64 {
	if m != nil {
		return m.Refs
	}
	return nil
}

type Relation struct {
	Id               *int64            `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Tags             []string          `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
	Members          []*RelationMember `protobuf:"bytes,3,rep,name=members" json:"members,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Relation) Reset()         { *m = Relation{} }
func (m *Relation) String() string { return proto.CompactTextString(m) }
func (*Relation) ProtoMessage()    {}

func (m *Relation) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Relation) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Relation) GetMembers() []*RelationMember {
	if m != nil {
		return m.Members
	}
	return nil
}

type RelationMember struct {
	MemberIds        *int64                     `protobuf:"varint,1,req,name=member_ids" json:"member_ids,omitempty"`
	MemberTypes      *RelationMember_MemberType `protobuf:"varint,2,req,name=member_types,enum=model.RelationMember_MemberType" json:"member_types,omitempty"`
	MemberRoles      *string                    `protobuf:"bytes,3,req,name=member_roles" json:"member_roles,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *RelationMember) Reset()         { *m = RelationMember{} }
func (m *RelationMember) String() string { return proto.CompactTextString(m) }
func (*RelationMember) ProtoMessage()    {}

func (m *RelationMember) GetMemberIds() int64 {
	if m != nil && m.MemberIds != nil {
		return *m.MemberIds
	}
	return 0
}

func (m *RelationMember) GetMemberTypes() RelationMember_MemberType {
	if m != nil && m.MemberTypes != nil {
		return *m.MemberTypes
	}
	return 0
}

func (m *RelationMember) GetMemberRoles() string {
	if m != nil && m.MemberRoles != nil {
		return *m.MemberRoles
	}
	return ""
}

func init() {
	proto.RegisterEnum("model.RelationMember_MemberType", RelationMember_MemberType_name, RelationMember_MemberType_value)
}
