// Code generated by protoc-gen-go.
// source: model.proto
// DO NOT EDIT!

package model

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type RelationMember_MemberType int32

const (
	RelationMember_NODE     RelationMember_MemberType = 0
	RelationMember_WAY      RelationMember_MemberType = 1
	RelationMember_RELATION RelationMember_MemberType = 2
)

var RelationMember_MemberType_name = map[int32]string{
	0: "NODE",
	1: "WAY",
	2: "RELATION",
}
var RelationMember_MemberType_value = map[string]int32{
	"NODE":     0,
	"WAY":      1,
	"RELATION": 2,
}

func (x RelationMember_MemberType) Enum() *RelationMember_MemberType {
	p := new(RelationMember_MemberType)
	*p = x
	return p
}
func (x RelationMember_MemberType) String() string {
	return proto.EnumName(RelationMember_MemberType_name, int32(x))
}
func (x RelationMember_MemberType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *RelationMember_MemberType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RelationMember_MemberType_value, data, "RelationMember_MemberType")
	if err != nil {
		return err
	}
	*x = RelationMember_MemberType(value)
	return nil
}

type Tag struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Val              *string `protobuf:"bytes,2,req,name=val" json:"val,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Tag) Reset()         { *this = Tag{} }
func (this *Tag) String() string { return proto.CompactTextString(this) }
func (*Tag) ProtoMessage()       {}

func (this *Tag) GetKey() string {
	if this != nil && this.Key != nil {
		return *this.Key
	}
	return ""
}

func (this *Tag) GetVal() string {
	if this != nil && this.Val != nil {
		return *this.Val
	}
	return ""
}

type Way struct {
	Id               *int64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Tags             []*Tag  `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
	Nodes            []int64 `protobuf:"varint,3,rep,packed,name=nodes" json:"nodes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Way) Reset()         { *this = Way{} }
func (this *Way) String() string { return proto.CompactTextString(this) }
func (*Way) ProtoMessage()       {}

func (this *Way) GetId() int64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

type Relation struct {
	Id               *int64            `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Tags             []*Tag            `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
	Members          []*RelationMember `protobuf:"bytes,3,rep,name=members" json:"members,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (this *Relation) Reset()         { *this = Relation{} }
func (this *Relation) String() string { return proto.CompactTextString(this) }
func (*Relation) ProtoMessage()       {}

func (this *Relation) GetId() int64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

type RelationMember struct {
	MemberIds        *int64                     `protobuf:"varint,1,req,name=member_ids" json:"member_ids,omitempty"`
	MemberTypes      *RelationMember_MemberType `protobuf:"varint,2,req,name=member_types,enum=model.RelationMember_MemberType" json:"member_types,omitempty"`
	MemberRoles      *string                    `protobuf:"bytes,3,req,name=member_roles" json:"member_roles,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (this *RelationMember) Reset()         { *this = RelationMember{} }
func (this *RelationMember) String() string { return proto.CompactTextString(this) }
func (*RelationMember) ProtoMessage()       {}

func (this *RelationMember) GetMemberIds() int64 {
	if this != nil && this.MemberIds != nil {
		return *this.MemberIds
	}
	return 0
}

func (this *RelationMember) GetMemberTypes() RelationMember_MemberType {
	if this != nil && this.MemberTypes != nil {
		return *this.MemberTypes
	}
	return 0
}

func (this *RelationMember) GetMemberRoles() string {
	if this != nil && this.MemberRoles != nil {
		return *this.MemberRoles
	}
	return ""
}

func init() {
	proto.RegisterEnum("model.RelationMember_MemberType", RelationMember_MemberType_name, RelationMember_MemberType_value)
}
