// Code generated by protoc-gen-go.
// source: fileformat.proto
// DO NOT EDIT!

package osmpbf

import proto "github.com/golang/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Blob struct {
	Raw               []byte `protobuf:"bytes,1,opt,name=raw" json:"raw,omitempty"`
	RawSize           *int32 `protobuf:"varint,2,opt,name=raw_size" json:"raw_size,omitempty"`
	ZlibData          []byte `protobuf:"bytes,3,opt,name=zlib_data" json:"zlib_data,omitempty"`
	LzmaData          []byte `protobuf:"bytes,4,opt,name=lzma_data" json:"lzma_data,omitempty"`
	OBSOLETEBzip2Data []byte `protobuf:"bytes,5,opt,name=OBSOLETE_bzip2_data" json:"OBSOLETE_bzip2_data,omitempty"`
	XXX_unrecognized  []byte `json:"-"`
}

func (this *Blob) Reset()         { *this = Blob{} }
func (this *Blob) String() string { return proto.CompactTextString(this) }
func (*Blob) ProtoMessage()       {}

func (this *Blob) GetRaw() []byte {
	if this != nil {
		return this.Raw
	}
	return nil
}

func (this *Blob) GetRawSize() int32 {
	if this != nil && this.RawSize != nil {
		return *this.RawSize
	}
	return 0
}

func (this *Blob) GetZlibData() []byte {
	if this != nil {
		return this.ZlibData
	}
	return nil
}

func (this *Blob) GetLzmaData() []byte {
	if this != nil {
		return this.LzmaData
	}
	return nil
}

func (this *Blob) GetOBSOLETEBzip2Data() []byte {
	if this != nil {
		return this.OBSOLETEBzip2Data
	}
	return nil
}

type BlobHeader struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Indexdata        []byte  `protobuf:"bytes,2,opt,name=indexdata" json:"indexdata,omitempty"`
	Datasize         *int32  `protobuf:"varint,3,req,name=datasize" json:"datasize,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BlobHeader) Reset()         { *this = BlobHeader{} }
func (this *BlobHeader) String() string { return proto.CompactTextString(this) }
func (*BlobHeader) ProtoMessage()       {}

func (this *BlobHeader) GetType() string {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return ""
}

func (this *BlobHeader) GetIndexdata() []byte {
	if this != nil {
		return this.Indexdata
	}
	return nil
}

func (this *BlobHeader) GetDatasize() int32 {
	if this != nil && this.Datasize != nil {
		return *this.Datasize
	}
	return 0
}

func init() {
}
