// Code generated by protoc-gen-go.
// source: cache/binary/messages.proto
// DO NOT EDIT!

package binary

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Relation_MemberType int32

const (
	Relation_NODE     Relation_MemberType = 0
	Relation_WAY      Relation_MemberType = 1
	Relation_RELATION Relation_MemberType = 2
)

var Relation_MemberType_name = map[int32]string{
	0: "NODE",
	1: "WAY",
	2: "RELATION",
}
var Relation_MemberType_value = map[string]int32{
	"NODE":     0,
	"WAY":      1,
	"RELATION": 2,
}

func (x Relation_MemberType) Enum() *Relation_MemberType {
	p := new(Relation_MemberType)
	*p = x
	return p
}
func (x Relation_MemberType) String() string {
	return proto.EnumName(Relation_MemberType_name, int32(x))
}
func (x Relation_MemberType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Relation_MemberType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Relation_MemberType_value, data, "Relation_MemberType")
	if err != nil {
		return err
	}
	*x = Relation_MemberType(value)
	return nil
}

type Node struct {
	Long             *uint32  `protobuf:"varint,1,req,name=long" json:"long,omitempty"`
	Lat              *uint32  `protobuf:"varint,2,req,name=lat" json:"lat,omitempty"`
	Tags             []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}

func (m *Node) GetLong() uint32 {
	if m != nil && m.Long != nil {
		return *m.Long
	}
	return 0
}

func (m *Node) GetLat() uint32 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *Node) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Way struct {
	Tags             []string `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
	Refs             []int64  `protobuf:"varint,2,rep,packed,name=refs" json:"refs,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Way) Reset()         { *m = Way{} }
func (m *Way) String() string { return proto.CompactTextString(m) }
func (*Way) ProtoMessage()    {}

func (m *Way) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Way) GetRefs() []int64 {
	if m != nil {
		return m.Refs
	}
	return nil
}

type Relation struct {
	Tags             []string              `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
	MemberIds        []int64               `protobuf:"varint,2,rep,name=member_ids" json:"member_ids,omitempty"`
	MemberTypes      []Relation_MemberType `protobuf:"varint,3,rep,name=member_types,enum=binary.Relation_MemberType" json:"member_types,omitempty"`
	MemberRoles      []string              `protobuf:"bytes,4,rep,name=member_roles" json:"member_roles,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *Relation) Reset()         { *m = Relation{} }
func (m *Relation) String() string { return proto.CompactTextString(m) }
func (*Relation) ProtoMessage()    {}

func (m *Relation) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Relation) GetMemberIds() []int64 {
	if m != nil {
		return m.MemberIds
	}
	return nil
}

func (m *Relation) GetMemberTypes() []Relation_MemberType {
	if m != nil {
		return m.MemberTypes
	}
	return nil
}

func (m *Relation) GetMemberRoles() []string {
	if m != nil {
		return m.MemberRoles
	}
	return nil
}

type DeltaCoords struct {
	Ids              []int64 `protobuf:"zigzag64,1,rep,packed,name=ids" json:"ids,omitempty"`
	Lats             []int64 `protobuf:"zigzag64,2,rep,packed,name=lats" json:"lats,omitempty"`
	Lons             []int64 `protobuf:"zigzag64,3,rep,packed,name=lons" json:"lons,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeltaCoords) Reset()         { *m = DeltaCoords{} }
func (m *DeltaCoords) String() string { return proto.CompactTextString(m) }
func (*DeltaCoords) ProtoMessage()    {}

func (m *DeltaCoords) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *DeltaCoords) GetLats() []int64 {
	if m != nil {
		return m.Lats
	}
	return nil
}

func (m *DeltaCoords) GetLons() []int64 {
	if m != nil {
		return m.Lons
	}
	return nil
}

func init() {
	proto.RegisterEnum("binary.Relation_MemberType", Relation_MemberType_name, Relation_MemberType_value)
}
